# used R-packages for xMAPr

- R: A Language and Environment for Statistical Computing (@R-base)
- bookdown: Authoring Books and Technical Documents with R Markdown (@R-bookdown)
- rmarkdown: Dynamic Documents for R (@R-rmarkdown)
- data.table: Extension of `data.frame` (@R-data.table)
- DT: A Wrapper of the JavaScript Library 'DataTables' (@R-DT)
- factoextra: Extract and Visualize the Results of Multivariate Data Analyses (@R-factoextra)
- FactoMineR: Multivariate Exploratory Data Analysis and Data Mining (@R-FactoMineR)
- ggrepel: Automatically Position Non-Overlapping Text Labels with 'ggplot2' (@R-ggrepel)
- ggsignif: Significance Brackets for 'ggplot2' (@R-ggsignif)
- gridExtra: Miscellaneous Functions for "Grid" Graphics (@R-gridExtra)
- heatmaply: Interactive Cluster Heat Maps Using 'plotly' (@R-heatmaply)
- knitr: A General-Purpose Package for Dynamic Report Generation in R (@R-knitr)
- magrittr: A Forward-Pipe Operator for R (@R-magrittr)
- minpack.lm: R Interface to the Levenberg-Marquardt Nonlinear Least-Squares Algorithm Found in MINPACK, Plus Support for Bounds (@R-minpack.lm)
- plotly: Create Interactive Web Graphics via 'plotly.js' (@R-plotly)
- RColorBrewer: ColorBrewer Palettes (@R-RColorBrewer)
- reshape: Flexibly Reshape Data (@R-reshape)
- reshape2: Flexibly Reshape Data: A Reboot of the Reshape Package (@R-reshape2)
- rlang: Functions for Base Types and Core R and 'Tidyverse' Features (@R-rlang)
- scales: Scale Functions for Visualization (@R-scales)
- shiny: Web Application Framework for R (@R-shiny)
- shinyalert: Easily Create Pretty Popup Messages (Modals) in 'Shiny' (@R-shinyalert)
- shinyBS: Twitter Bootstrap Components for Shiny (@R-shinyBS)
- shinydashboard: Create Dashboards with 'Shiny' (@R-shinydashboard)
- shinyFiles: A Server-Side File System Viewer for Shiny (@R-shinyFiles)
- shinyjs: Easily Improve the User Experience of Your Shiny Apps in Seconds (@R-shinyjs)
- shinyWidgets: Custom Inputs Widgets for Shiny (@R-shinyWidgets)
- tidyverse: Easily Install and Load the 'Tidyverse' (@R-tidyverse)

